- name: Sudoku
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml
    - vars/solver/game-3.yml

  tasks:
    - name: install platform42.neo4j dependencies
      ansible.builtin.include_tasks: tasks/dependencies/neo4j.yml

    - name: check puzzle solved without guessing
      ansible.builtin.include_tasks: tasks/solver/deterministic/puzzle-solved.yml

    - name: initialize guess level
      ansible.builtin.set_fact:
        guess_level: 0
      when: 
        - not puzzle_solved

    - name: guess based solver
      ansible.builtin.include_tasks: tasks/solver/heuristic/guess-or-solve.yml
      when:
        - not puzzle_solved

    - name: print sudoku solution
      ansible.builtin.include_tasks: tasks/solver/visualize.yml


