- name: Sudoku
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml
    - vars/solver/initial.yml

  tasks:
    - name: install platform42.neo4j dependencies
      ansible.builtin.include_tasks: tasks/dependencies/neo4j.yml

    # step 1: initial moves
    - name: calculate unforced moves
      ansible.builtin.include_tasks: tasks/solver/initial.yml
      loop: "{{ cells_initial }}"
    
    - name: initialize for forced moves
      ansible.builtin.set_fact:
        has_forced_moves: True

    # step 2: forced moves
    - name: check for forced moves
      ansible.builtin.include_tasks: tasks/solver/forced.yml
      when:
        - has_forced_moves

    # print board
    - name: print sudoku board
      ansible.builtin.include_tasks: tasks/solver/visualize.yml
