- name: Sudoku
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml
    - vars/solver/initial.yml

  tasks:
    - name: install platform42.neo4j dependencies
      ansible.builtin.include_tasks: tasks/dependencies/neo4j.yml

    # step 1: set initial values
    - name: set initial values for solving
      ansible.builtin.include_tasks: tasks/solver/initial.yml
      loop: "{{ cells_initial }}"
    
    # print board
    - name: print sudoku board
      ansible.builtin.include_tasks: tasks/solver/visualize.yml

    # step 2: forced values
    - name: set initial values for solving
      ansible.builtin.include_tasks: tasks/solver/forced.yml
