- name: Sudoku
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml
    - vars/solver/game-2.yml

  tasks:
    - name: install platform42.neo4j dependencies
      ansible.builtin.include_tasks: tasks/dependencies/neo4j.yml

    # step 1: execute initial moves
    - name: calculate unforced moves
      ansible.builtin.include_tasks: tasks/solver/deterministic/initial-moves.yml
      loop: "{{ cells_initial }}"
    
    # step 2: execute deterministic moves
    - name: forced solver
      ansible.builtin.include_tasks: tasks/solver/deterministic/forced-moves.yml

    # step 3: guessing needed?
    - name: check puzzle solved without guessing
      ansible.builtin.include_tasks: tasks/solver/deterministic/puzzle-solved.yml

    # step 4: execute by guessing
    - name: guess based solver
      ansible.builtin.include_tasks: tasks/solver/heuristic/guess.yml
      when:
        - not puzzle_solved

    - name: print sudoku solution
      ansible.builtin.include_tasks: tasks/solver/visualize.yml

