- name: Sudoku
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml
    - vars/vertices/cells.yml
    - vars/edges/sees.yml
    - vars/solver/cell.yml

  tasks:
    - name: install platform42.neo4j dependencies
      ansible.builtin.include_tasks: tasks/dependencies/neo4j.yml

#    - name: cleanup graph database
#      ansible.builtin.include_tasks: tasks/database/database.yml

#    - name: create 3x3 Sudoku nodes
#      ansible.builtin.include_tasks: tasks/vertices/cells.yml
#      loop: "{{ cells }}"

#    - name: create 3x3 Sudoku relationships
#      ansible.builtin.include_tasks: tasks/edges/sees.yml
#      loop: "{{ sees }}"

    - name: set initial values for solving
      ansible.builtin.include_tasks: tasks/solver/initial.yml
      loop: "{{ cells_initial }}"
