- name: Sudoku
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml
    - vars/vertices/cells.yml
    - vars/edges/sees.yml

  tasks:
    - name: install platform42.neo4j dependencies
      ansible.builtin.include_tasks: tasks/dependencies/neo4j.yml

    - name: cleanup graph database
      ansible.builtin.include_tasks: tasks/database/database.yml

    - name: create 3x3 Sudoku nodes
      ansible.builtin.include_tasks: tasks/vertices/bulk/cells.yml

    - name: create Sudoku relationships
      ansible.builtin.include_tasks: tasks/edges/bulk/sees.yml

