- name: Sudoku
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml
    - vars/vertices/row_1.yml
    - vars/vertices/row_2.yml
    - vars/vertices/row_3.yml
    - vars/vertices/row_4.yml
    - vars/vertices/row_5.yml
    - vars/vertices/row_6.yml
    - vars/vertices/row_7.yml
    - vars/vertices/row_8.yml
    - vars/vertices/row_9.yml
    - vars/edges/sees.yml

  tasks:
    - name: install platform42.neo4j dependencies
      ansible.builtin.include_tasks: tasks/dependencies/neo4j.yml

    - name: cleanup graph database
      ansible.builtin.include_tasks: tasks/database/database.yml

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/vertices/cells.yml
      loop: "{{ cells_row_1 }}"

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/vertices/cells.yml
      loop: "{{ cells_row_2 }}"

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/vertices/cells.yml
      loop: "{{ cells_row_3 }}"

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/vertices/cells.yml
      loop: "{{ cells_row_4 }}"

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/vertices/cells.yml
      loop: "{{ cells_row_5 }}"

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/vertices/cells.yml
      loop: "{{ cells_row_6 }}"

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/vertices/cells.yml
      loop: "{{ cells_row_7 }}"

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/vertices/cells.yml
      loop: "{{ cells_row_8 }}"

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/vertices/cells.yml
      loop: "{{ cells_row_9 }}"

    - name: create 3x3 vertex matrix
      ansible.builtin.include_tasks: tasks/edges/sees.yml
      loop: "{{ sees }}"